routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Entities\Accounts\User;
use App\Entities\Image;
use App\Entities\Products\Product;

Route::get('/', function () {
   dd(App());
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index');

Route::get('files/{path}', 'MediaController@file')->name('media.proxy')
    ->where(['path' => '.*']);

//Admin routes
Route::group([
    'as' => 'admin.',
    'prefix' => 'sysadmin',
    'namespace' => 'Admin'
], function () {
    Route::get('/login.html', 'LoginController@showLoginForm')->name('login');
    Route::post('/login.html', 'LoginController@login');
    Route::post('/logout.html', 'LoginController@logout')->name('logout');
//    Dashboard
    Route::get('/dashboard.html', 'DashboardController@index')->name('dashboard');
//    End Dashboard

//    Products
    Route::get('/product.html', 'ProductController@index')->name('product');
    Route::get('/product.html/create.html', 'ProductController@create')
        ->name('product.create');
    Route::post('/product.html/store.html', 'ProductController@store')
        ->name('product.store');
    Route::get('product.html/{product}/edit.html', 'ProductController@edit')
        ->name('product.edit');
    Route::post('product.html/{product}/edit.html', 'ProductController@update')
        ->name('product.update');
    Route::post('product.html/{product}/delete.html', 'ProductController@destroy')
        ->name('product.destroy');
    Route::get('product.html/{product}/image.html', 'ProductController@image')
        ->name('product.image');
    Route::post('product.html/{product}/image.html', 'ProductController@imageStore')
        ->name('product.image.store');
    Route::post('product.html/{product}/image.html/{image}', 'ProductController@imageDestroy')
        ->name('product.image.destroy');
    Route::bind('product', function ($value) {
        $product = Product::bySlug($value);

        return ($product instanceof Product) ? $product : abort(404);
    });
    Route::bind('image', function ($value) {
        $product = Image::bySlug($value);

        return ($product instanceof Image) ? $product : abort(404);
    });
    //    end Products

    //    Start Users
    Route::get('user.html', 'UserController@index')->name('user');
});

resources/views/layouts/admin/app.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andromeda
 * Date: 28/01/18
 * Time: 13:59
 */
?>
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ $pageMeta or 'The Admin' }}</title>
    <meta name="keywords" content="{{ $pageMeta['keywords'] or '' }}">
    <meta name="description" content="{{ $pageMeta['description'] or '' }}">
    <meta name="token" content="{{ csrf_token() }}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,300i"
          rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/core.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.min.css') }}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{{ asset('img/apple-touch-icon.png') }}">
    <link rel="icon" href="{{ asset('img/favicon.png') }}">
</head>

<!-- Preloader -->
<div class="preloader">
    <div class="spinner-dots">
        <span class="dot1"></span>
        <span class="dot2"></span>
        <span class="dot3"></span>
    </div>
</div>

@yield('content')
<!-- Scripts -->
<script src="{{ asset('js/core.min.js') }}"></script>
<script src="{{ asset('js/app.min.js') }}"></script>
<script src="{{ asset('js/script.min.js') }}"></script>
</html>

resources/views/layouts/admin/master.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andromeda
 * Date: 28/01/18
 * Time: 13:59
 */
?>
        <!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ $pageTitle or 'The Admin' }}</title>
    <meta name="keywords" content="{{ $pageMeta['keywords'] or '' }}">
    <meta name="description" content="{{ $pageMeta['description'] or '' }}">
    <meta name="token" content="{{ csrf_token() }}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,300i"
          rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/core.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.min.css') }}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{{ asset('img/apple-touch-icon.png') }}">
    <link rel="icon" href="{{ asset('img/favicon.png') }}">
    <style>
        @yield('css')
    </style>
</head>
<body class="animsition">
<!-- Preloader -->
<div class="preloader">
    <div class="spinner-dots">
        <span class="dot1"></span>
        <span class="dot2"></span>
        <span class="dot3"></span>
    </div>
</div>

<!-- Sidebar -->
@include('layouts.admin.sidebar')

@yield('content')
<!-- Scripts -->
<script src="{{ asset('js/core.min.js') }}"></script>
<script src="{{ asset('js/app.min.js') }}"></script>
<script src="{{ asset('js/script.min.js') }}"></script>
<script type="text/javascript">
    @yield('js')
</script>
</body>
</html>

resources/views/layouts/admin/sidebar.blade.php
<!-- Sidebar -->
<aside class="sidebar sidebar-expand-lg sidebar-iconic">
    <header class="sidebar-header">
        <span class="logo text-center">
          <a href="{{ route('admin.') }}"><img src="http://thetheme.io/theadmin/assets/img/logo-icon-light.png" alt="logo"></a>
        </span>
    </header>

    <nav class="sidebar-navigation">

        <ul class="menu">

            <li class="menu-item active">
                <a class="menu-link" href="{{ route('admin.dashboard') }}">
                    <span class="icon ti-home"></span>
                    <span class="title">Dashboard</span>
                </a>
            </li>

            <li class="menu-item">
                <a class="menu-link" href="{{ route('admin.product') }}">
                    <span class="icon ti-briefcase"></span>
                    <span class="title">Projects</span>
                </a>
            </li>

            <li class="menu-item">
                <a class="menu-link" href="{{ route('admin.user') }}">
                    <span class="icon ti-user"></span>
                    <span class="title">Clients</span>
                </a>
            </li>

            <li class="menu-item">
                <a class="menu-link" href="#">
                    <span class="icon ti-email"></span>
                    <span class="title">Messages</span>
                    <span class="badge badge-pill badge-info">2</span>
                </a>
            </li>

            <li class="menu-item">
                <a class="menu-link" href="#">
                    <span class="icon ti-settings"></span>
                    <span class="title">Settings</span>
                </a>
            </li>

        </ul>
    </nav>

</aside>
<!-- END Sidebar -->


    <!-- Topbar -->
    <header class="topbar">
      <div class="topbar-left">
        <span class="topbar-btn sidebar-toggler"><i>&#9776;</i></span>

        <a class="topbar-btn d-none d-md-block" href="#" data-provide="fullscreen tooltip" title="Fullscreen">
          <i class="material-icons fullscreen-default">fullscreen</i>
          <i class="material-icons fullscreen-active">fullscreen_exit</i>
        </a>
      </div>

      <div class="topbar-right">
        <div class="topbar-divider"></div>

        <ul class="topbar-btns">
          <li class="dropdown">
            <span class="topbar-btn" data-toggle="dropdown"><img class="avatar" src="{{ asset('img/avatar/1.jpg') }}" alt="..."></span>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="page/profile.html"><i class="ti-user"></i> Profile</a>
              <a class="dropdown-item" href="page-app/mailbox.html">
                <div class="flexbox">
                  <i class="ti-email"></i>
                  <span class="flex-grow">Inbox</span>
                  <span class="badge badge-pill badge-info">5</span>
                </div>
              </a>
              <a class="dropdown-item" href="#"><i class="ti-settings"></i> Settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="page-extra/user-lock-1.html"><i class="ti-lock"></i> Lock</a>
              <a class="dropdown-item" href="page-extra/user-login-3.html"><i class="ti-power-off"></i> Logout</a>
            </div>
          </li>

          <!-- Notifications -->
          <li class="dropdown d-none d-md-block">
            <span class="topbar-btn has-new" data-toggle="dropdown"><i class="ti-bell"></i></span>
            <div class="dropdown-menu dropdown-menu-right">

              <div class="media-list media-list-hover media-list-divided media-list-xs">
                <a class="media media-new" href="#">
                  <span class="avatar bg-success"><i class="ti-user"></i></span>
                  <div class="media-body">
                    <p>New user registered</p>
                    <time datetime="2017-07-14 20:00">Just now</time>
                  </div>
                </a>

                <a class="media" href="#">
                  <span class="avatar bg-info"><i class="ti-shopping-cart"></i></span>
                  <div class="media-body">
                    <p>New order received</p>
                    <time datetime="2017-07-14 20:00">2 min ago</time>
                  </div>
                </a>

                <a class="media" href="#">
                  <span class="avatar bg-warning"><i class="ti-face-sad"></i></span>
                  <div class="media-body">
                    <p>Refund request from <b>Ashlyn Culotta</b></p>
                    <time datetime="2017-07-14 20:00">24 min ago</time>
                  </div>
                </a>

                <a class="media" href="#">
                  <span class="avatar bg-primary"><i class="ti-money"></i></span>
                  <div class="media-body">
                    <p>New payment has made through PayPal</p>
                    <time datetime="2017-07-14 20:00">53 min ago</time>
                  </div>
                </a>
              </div>

              <div class="dropdown-footer">
                <div class="left">
                  <a href="#">Read all notifications</a>
                </div>

                <div class="right">
                  <a href="#" data-provide="tooltip" title="Mark all as read"><i class="fa fa-circle-o"></i></a>
                  <a href="#" data-provide="tooltip" title="Update"><i class="fa fa-repeat"></i></a>
                  <a href="#" data-provide="tooltip" title="Settings"><i class="fa fa-gear"></i></a>
                </div>
              </div>

            </div>
          </li>
          <!-- END Notifications -->
        </ul>

      </div>
    </header>
    <!-- END Topbar -->