routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Entities\Accounts\User;
use App\Entities\Image;
use App\Entities\Products\Product;

Route::get('/', function () {
   dd(App());
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index');

Route::get('files/{path}', 'MediaController@file')->name('media.proxy')
    ->where(['path' => '.*']);

//Admin routes
Route::group([
    'as' => 'admin.',
    'prefix' => 'sysadmin',
    'namespace' => 'Admin'
], function () {
    Route::get('/login.html', 'LoginController@showLoginForm')->name('login');
    Route::post('/login.html', 'LoginController@login');
    Route::post('/logout.html', 'LoginController@logout')->name('logout');
//    Dashboard
    Route::get('/dashboard.html', 'DashboardController@index')->name('dashboard');
//    End Dashboard

//    Products
    Route::get('/product.html', 'ProductController@index')->name('product');
    Route::get('/product.html/create.html', 'ProductController@create')
        ->name('product.create');
    Route::post('/product.html/store.html', 'ProductController@store')
        ->name('product.store');
    Route::get('product.html/{product}/edit.html', 'ProductController@edit')
        ->name('product.edit');
    Route::post('product.html/{product}/edit.html', 'ProductController@update')
        ->name('product.update');
    Route::post('product.html/{product}/delete.html', 'ProductController@destroy')
        ->name('product.destroy');
    Route::get('product.html/{product}/image.html', 'ProductController@image')
        ->name('product.image');
    Route::post('product.html/{product}/image.html', 'ProductController@imageStore')
        ->name('product.image.store');
    Route::post('product.html/{product}/image.html/{image}', 'ProductController@imageDestroy')
        ->name('product.image.destroy');
    Route::bind('product', function ($value) {
        $product = Product::bySlug($value);

        return ($product instanceof Product) ? $product : abort(404);
    });
    Route::bind('image', function ($value) {
        $product = Image::bySlug($value);

        return ($product instanceof Image) ? $product : abort(404);
    });
    //    end Products

    //    Start Users
    Route::get('user.html', 'UserController@index')->name('user');
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Core\Controllers\ResourceControl;
use App\Entities\Categories\Category;
use App\Entities\Image;
use App\Entities\Products\Product;
use App\Jobs\Images\CreateImage;
use App\Jobs\Images\DeleteImage;
use App\Jobs\Products\CreateProduct;
use App\Jobs\Products\DeleteProduct;
use App\Jobs\Products\UpdateProduct;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    use ResourceControl;

    public function __construct()
    {
        $this->middleware('admin')->except('logout');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index()
    {
        $product = Product::with(['images','categories', 'attr' => function ($query) {
            $query->orderBy('created_at', 'desc');
        }])->paginate(10);

        $this->setData('pageTitle', 'Product - Dashboard');
        $this->setData('products', $product);

        return view('admin.products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        $data = [
            'categories' => $categories
        ];

        return view('admin.products.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->dispatch(new CreateProduct($request));
        } catch (\Exception $exception) {
            return redirect()->back()->with('Error', 'Produk gagal');
        }

        return redirect()->route('admin.product')
            ->with('success', 'Produk telah dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $attr = $product->attr()->get();
        $categories = Category::all();
        $this->setData('attr', $attr);
        $this->setData('categories', $categories);
        $this->setData('product', $product);
        $this->setData('pageTitle', 'Edit barang: '. $product->name);

        return view('admin.products.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        try {
            $this->dispatch(new UpdateProduct($request, $product));
        } catch (\Exception $exception) {
            return redirect()->back()->with('errors', 'Cant update');
        }

        return redirect()->route('admin.product')
            ->with('success', 'Produk telah di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        try {
            $this->dispatch(new DeleteProduct($product));
        } catch (\Exception $exception) {
            return redirect()->back()->with('errors', 'Cant Delete');
        }

        return redirect()->route('admin.product')
            ->with('success', 'Produk telah di Hapus');
    }

    public function image(Product $product)
    {
        $this->setData('product', $product);
        $this->setData('pageTitle', $product->name);

        return view('admin.products.images');
    }

    public function imageStore(Request $request, Product $product)
    {
        try {
            $this->dispatch(new CreateImage($request, $product));
        } catch (\Exception $exception) {
            return redirect()->back()->with('errors', 'Cant create');
        }

        return redirect()->route('admin.product.image', $product->slug)
            ->with('success', 'gambar telah di buat');
    }

    public function imageDestroy(Request $request,Product $product, Image $image)
    {
        try {
            $this->dispatch(new DeleteImage($request, $product, $image));
        } catch (\Exception $exception) {
            return redirect()->back()->with('errors', 'Cant Delete');
        }

        return redirect()->route('admin.product.image', $product->slug)
            ->with('success', 'gambar telah di Hapus');
    }
}

resources/views/admin/products/create.blade.php
@php
    /**
     * Created by PhpStorm.
     * User: andromeda
     * Date: 30/01/18
     * Time: 12:19
     */
@endphp

@extends('layouts.admin.master')

@section('css')
    .col-form-label {
    font-size: 15px;
    }
    .red{
    color: #d34055;
    }
@endsection

@section('content')

    <main class="main-container">
        <div class="main-content">

            <div class="header-info">
                <div class="left">
                    <h2 class="header-title"><strong>Create</strong> Product</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.product') }}">Product</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>

            <form action="{{ route('admin.product.store') }}" method="POST"
                  class="form-horizontal" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-title">
                                <h3><strong>Data</strong> Barang</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name" class="col-form-label">Name <span class="red">*</span></label>
                                    <input id="name" type="text" class="form-control" name="name"
                                           placeholder="Nama Barang" required>
                                </div>
                                <div class="form-group">
                                    <label for="categories" class="col-form-label">Kategori Barang <span
                                                class="red">*</span></label>
                                    <select id="categories.0" name="categories[]" data-provide="selectpicker"
                                            class="form-control" multiple
                                            data-max-options="2" required>
                                        @foreach($categories as $value)
                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-title">
                                <h3><strong>Gambar</strong> Barang <span class="red">*</span></h3>
                            </div>
                            <div class="card-body">
                                <input id="images.0" type="file" data-provide="dropify" name="images[]" multiple required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-title">
                                <h3><strong>Detail</strong> Barang</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="attr.0" class="col-form-label">Harga Barang <span
                                                class="red">*</span></label>
                                    <input id="attr.0" type="number" class="form-control" name="attr[price]"
                                           placeholder="Harga Barang" required>
                                </div>
                                <div class="form-group">
                                    <label for="attr.1" class="col-form-label">Perkiraan Berat <span
                                                class="red">*</span></label>
                                    <input id="attr.1" type="number" class="form-control" name="attr[weight]"
                                           placeholder="Perkiraan Berat (dalam gram)" required>
                                </div>
                                <div class="form-group">
                                    <label for="attr.2" class="col-form-label">Stok <span class="red">*</span></label>
                                    <input id="attr.2" type="number" class="form-control" name="attr[stock]"
                                           placeholder="Stok barang" required>
                                </div>
                                <div class="form-group">
                                    <label for="attr.3" class="col-form-label">Kondisi Barang <span class="red">*</span></label>
                                    <br>
                                    <div class="form-check form-check-inline">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="attr[condition]"
                                                   id="attr.3" value="new"> Baru
                                        </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="attr[condition]"
                                                   id="attr.3" value="second"> Bekas
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="attr.4" class="col-form-label">Ukuran <span class="red">*</span></label>
                                    <input id="attr.4" type="text" class="form-control" name="attr[size]"
                                           placeholder="Ukuran barang (Harap isi dengan benar)" required>
                                </div>
                                <div class="form-group">
                                    <label for="attr.5" class="col-form-label">Deskripsi Barang <span
                                                class="red">*</span></label>
                                    <textarea id="attr.5" class="form-control" name="attr[description]"
                                              placeholder="Deskripsi" rows="6" required></textarea>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-label btn-primary">
                                        <label><i class="ti-check"></i></label> Tambah
                                    </button>
                                    <a href="{{ route('admin.dashboard') }}" data-provide="animsition">
                                        <button class="btn btn-label btn-warning">
                                            <label><i class="ti-arrow-left"></i></label> Batal
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </main>

@endsection

resources/views/admin/products/images.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andromeda
 * Date: 01/02/18
 * Time: 20:23
 */
?>
@extends('layouts.admin.master')

@section('content')

    <main class="main-container">
        <div class="main-content">
            <header class="header">
                <div class="header-info">
                    <div class="left">
                        <h2 class="header-title">
                            <strong>{{ $product->name }}</strong></h2>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.product') }}">Product</a></li>
                            <li class="breadcrumb-item">Image</li>
                        </ol>
                    </div>
                </div>
            </header>
            <div class="row">
                @foreach($product->images as $value)
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-title">{{ $value->slug }}</div>
                            <div class="card-body">
                                <img src="{{ route('media.proxy', $value->src) }}" alt="{{ $value->slug }}">
                                <table style="margin: auto;">
                                    <td>
                                        <form method="post"
                                              onclick="return confirm('Apakah anda yakin ' +
                                       'ingin menghapus gambar ini')"
                                              action="{{ route('admin.product.image.destroy',
                                              [$product->slug, $value->slug]) }}">
                                            {!! csrf_field() !!}
                                            <button class="btn btn-sm btn-label btn-danger">
                                                <label><i class="ti-trash"></i></label> Hapus
                                            </button>
                                        </form>
                                    </td>
                                </table>
                            </div>
                        </div>
                    </div>
                @endforeach
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-title">
                            <center><strong>Tambah Gambar</strong></center>
                        </div>
                        <div class="card-body" style="margin: auto;">
                            <form action="{{ route('admin.product.image.store', $product->slug) }}" method="post" enctype="multipart/form-data">
                                {!! csrf_field() !!}
                                <input id="images.0" type="file" data-provide="dropify" name="images[]" multiple required>
                                <center><div class="fab" style="margin-top: 10px;">
                                    <button class="btn btn-float btn-primary"><i class="ti-plus"></i></button>
                                </div></center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

@endsection

resources/views/admin/products/index.blade.php
@php
    /**
     * Created by PhpStorm.
     * User: andromeda
     * Date: 29/01/18
     * Time: 11:16
     */
@endphp

@extends('layouts.admin.master')

@section('content')
    <main class="main-container">
        <div class="main-content">
            <header class="header">
                <div class="header-info">
                    <div class="left">
                        <h2 class="header-title">
                            <strong>Product</strong></h2>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                            <li class="breadcrumb-item active">Product</li>
                        </ol>
                    </div>
                </div>
            </header>
            <div class="card">
                <div class="card-title">
                    <form class="lookup lookup-right lookup-lg">
                        <input type="text" placeholder="Search...">
                    </form>
                    <a href="{{ route('admin.product.create') }}" data-provide="animsition">
                        <button class="btn btn-lg btn-round btn-info">Add Product</button>
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-striped" style="text-align: center">
                        <thead>
                        <tr>
                            <th style="text-align: center">#</th>
                            <th style="text-align: center">Name</th>
                            <th style="text-align: center">Condition</th>
                            <th style="text-align: center">Gambar</th>
                            <th style="text-align: center">Created_at</th>
                            <th style="text-align: center">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $key => $value)
                            <tr>
                                <td scope="row">{{ $key + 1 }}</td>
                                <td>{{ $value->name }}</td>
                                <td>
                                    @if($value->attr->condition == 'new')
                                        <span class="badge badge-success">New</span>
                                    @else
                                        <span class="badge badge-warning">Second</span>
                                    @endif
                                </td>

                                <td>
                                    <a href="{{ route('admin.product.image', $value->slug) }}">{{ count($value->images) }}</a>
                                </td>
                                <td>{{ date('d-m-Y', strtotime($value->created_at)) }}</td>
                                <td>
                                    <a href="{{ route('admin.product.edit', $value->slug) }}">
                                        <button class="btn btn-sm btn-label btn-info">
                                            <label><i class="ti-pencil"></i></label> Edit
                                        </button>
                                    </a>
                                    <form method="post"
                                          onclick="return confirm('Apakah anda yakin ' +
                                       'ingin menghapus barang ini')"
                                          action="{{ route('admin.product.destroy', $value->slug) }}">
                                        {!! csrf_field() !!}
                                        <button class="btn btn-sm btn-label btn-danger">
                                            <label><i class="ti-trash"></i></label> Hapus
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $products->links('layouts.components.pagination') }}
                </div>
            </div>
        </div>
    </main>
@endsection